version: "3"
services:
  server:
    image: gitea/gitea
    container_name: gitea-server
    ports:
      - "8080:3000"
    env_file:
      - stack.env
    restart: always
    volumes:
      - /data/gitea/gitea:/data:z
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db

  db:
    image: mysql
    container_name: gitea-db
    restart: always
    env_file:
      - stack.env
    volumes:
      - /data/gitea/mysql:/var/lib/mysql:z