version: '3.9'
services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    command: --schedule '0 0 4 * * *' --rolling-restart --cleanup
    security_opt:
      - label:disable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock