version: '3'
services:
  db:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    env_file:
      - stack.env
    volumes:
      - /data/mariadb:/var/lib/mysql:z

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    env_file:
      - stack.env